# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_pb2 as trading__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """============ Service Definition ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitKlines = channel.unary_unary(
                '/trading.TradingService/SubmitKlines',
                request_serializer=trading__pb2.SubmitKlinesRequest.SerializeToString,
                response_deserializer=trading__pb2.SubmitKlinesResponse.FromString,
                _registered_method=True)
        self.CalculatePens = channel.unary_unary(
                '/trading.TradingService/CalculatePens',
                request_serializer=trading__pb2.CalculatePensRequest.SerializeToString,
                response_deserializer=trading__pb2.CalculatePensResponse.FromString,
                _registered_method=True)
        self.CalculateSegments = channel.unary_unary(
                '/trading.TradingService/CalculateSegments',
                request_serializer=trading__pb2.CalculateSegmentsRequest.SerializeToString,
                response_deserializer=trading__pb2.CalculateSegmentsResponse.FromString,
                _registered_method=True)
        self.GetMACD = channel.unary_unary(
                '/trading.TradingService/GetMACD',
                request_serializer=trading__pb2.GetMACDRequest.SerializeToString,
                response_deserializer=trading__pb2.GetMACDResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/trading.TradingService/HealthCheck',
                request_serializer=trading__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=trading__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/trading.TradingService/GetStatus',
                request_serializer=trading__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=trading__pb2.GetStatusResponse.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """============ Service Definition ============

    """

    def SubmitKlines(self, request, context):
        """Submit K-line data for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculatePens(self, request, context):
        """Calculate pens using pen theory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateSegments(self, request, context):
        """Calculate line segments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMACD(self, request, context):
        """Get MACD indicator values
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get overall system status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitKlines': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitKlines,
                    request_deserializer=trading__pb2.SubmitKlinesRequest.FromString,
                    response_serializer=trading__pb2.SubmitKlinesResponse.SerializeToString,
            ),
            'CalculatePens': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculatePens,
                    request_deserializer=trading__pb2.CalculatePensRequest.FromString,
                    response_serializer=trading__pb2.CalculatePensResponse.SerializeToString,
            ),
            'CalculateSegments': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateSegments,
                    request_deserializer=trading__pb2.CalculateSegmentsRequest.FromString,
                    response_serializer=trading__pb2.CalculateSegmentsResponse.SerializeToString,
            ),
            'GetMACD': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMACD,
                    request_deserializer=trading__pb2.GetMACDRequest.FromString,
                    response_serializer=trading__pb2.GetMACDResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=trading__pb2.HealthCheckRequest.FromString,
                    response_serializer=trading__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=trading__pb2.GetStatusRequest.FromString,
                    response_serializer=trading__pb2.GetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """============ Service Definition ============

    """

    @staticmethod
    def SubmitKlines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/SubmitKlines',
            trading__pb2.SubmitKlinesRequest.SerializeToString,
            trading__pb2.SubmitKlinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculatePens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/CalculatePens',
            trading__pb2.CalculatePensRequest.SerializeToString,
            trading__pb2.CalculatePensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateSegments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/CalculateSegments',
            trading__pb2.CalculateSegmentsRequest.SerializeToString,
            trading__pb2.CalculateSegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMACD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetMACD',
            trading__pb2.GetMACDRequest.SerializeToString,
            trading__pb2.GetMACDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/HealthCheck',
            trading__pb2.HealthCheckRequest.SerializeToString,
            trading__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetStatus',
            trading__pb2.GetStatusRequest.SerializeToString,
            trading__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
